services:
  mrsm-dev:
    image: "bmeares/meerschaum"
    entrypoint: ["/scripts/dev.sh"]
    network_mode: "host"
    init: true
    stdin_open: true
    tty: true
    volumes:
      - "./:/app"
      - "./scripts/docker:/scripts"
      - "dev_root:/meerschaum"

volumes:
  dev_root:
